[package]
name = "async_internals"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
anyhow = "1"
futures = "0.3"
pin-project = "1"
tokio = { version = "1", features = ["full"] }
