@startuml
title 过程宏定义使用流程
|Cargo.toml|
start
:打开过程宏;
floating note
[lib]
proc-macro = true
end note
|src/lib.rs|
:定义过程宏;
floating note right
#[proc_macro]
pub fn query(input: TokenStream) -> TokenStream {
    // 只有修改代码之后再次编译才会执行
    println!("{:#?}", input);
    "fn hello() { println!(\"Hello world!\"); }"
        .parse()
        .unwrap()
}
end note
|examples/调用代码|
:使用过程宏;
floating note
use macros::query;

fn main() {
    // query!(SELECT * FROM users WHERE age > 10);
    query!(SELECT * FROM users u JOIN (SELECT * from profiles p) WHERE u.id = p.id);
    hello()
}
end note
|Terminal|
:查看打印的TokenStream;
floating note
cargo run --example query > examples/query_output.txt
end note
stop
@enduml